<?php

namespace AppBundle\Repository;

/**
 * GroupLRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupLRepository extends \Doctrine\ORM\EntityRepository
{
}
